### ISSUE TITLE
loading samples in RAM?

### ISSUE THREAD

**Issue by sonejostudios** [sonejostudios/superboucle#5]
In my point of (user-) view it would be better to load all samples from only ONE song (instead of ll songs in playlist). Because users could have a lot of songs with long loops (~ 64 beats).
exemple: I've got 1 song with 15 samples with 64 beats each (~80mb). If this song would have 64 clips that would be a lot of data to load for only ONE song... this is fine but if each song is like this that would use too much RAM at all.

**Comment by IARI** [comment]
Since for now it's working and it seems to be working nicely I propose to postpone a final decision on this question - maybe lets ask that again, when you have enough sample songs that use up a lot of memory, then we can do some performance power-testing :)

**Comment by sonejostudios** [comment]
How is it right now? all songs are loaded in RAM or only the current song?

**Comment by sonejostudios** [comment]
since all songs are loaded in RAM, reloading a previous played song loads it with the last play status (the loops are playing). Very weird on stage. I'd would prefer to load the song in the RAM while loading the song (not all while loading the playlist).
